typedef enum request_type {
	GET_HELLO,
	GET_INSTRUCTION,
	GET_PAYLOAD
} REQUEST_TYPE;

typedef enum response_type {
	RETURN_HELLO,
	RETRUN_INSTRUCTION,
	RETURN_PAYLOAD
} RESPONSE_TYPE;

typedef enum payload_type {
	DLL_PAYLOAD,
	EXE_PAYLOAD,
	ABORT_PAYLOAD
} PAYLOAD_TYPE;